# Generated by Django 5.1.6 on 2025-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='resources/'),
        ),
    ]
