# Generated by Django 5.1.1 on 2025-08-18 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerbuilding',
            name='stored_xp',
        ),
        migrations.AlterField(
            model_name='playerbuilding',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype'),
        ),
        migrations.CreateModel(
            name='BuildingLevelCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_costs', to='core.buildingtype')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype')),
            ],
            options={
                'unique_together': {('building_type', 'level', 'resource_type')},
            },
        ),
    ]
