# Generated by Django 5.1.6 on 2025-09-02 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resourcetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cost_amount', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('promo_rate', models.FloatField(default=0.03, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('normal_rate', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pull_cost_banners', to='core.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='BannerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_promotional', models.BooleanField(default=False)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.banner')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_entries', to='core.hero')),
            ],
        ),
        migrations.CreateModel(
            name='BannerPullLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(choices=[('hero_promo', 'Héroe promocional'), ('hero_normal', 'Héroe normal'), ('reward', 'Recompensa'), ('none', 'Ninguno')], max_length=20)),
                ('reward_snapshot', models.JSONField(blank=True, help_text='Listado de items de recompensa otorgados', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_logs', to='core.banner')),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hero')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_logs', to='core.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BannerReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Recompensa', max_length=100)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.banner')),
            ],
        ),
        migrations.CreateModel(
            name='BannerRewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_amount', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.bannerreward')),
            ],
        ),
        migrations.AddConstraint(
            model_name='banner',
            constraint=models.CheckConstraint(condition=models.Q(('promo_rate__gte', 0.0), ('normal_rate__gte', 0.0), ('promo_rate__lte', 1.0), ('normal_rate__lte', 1.0)), name='banner_rates_sum_le_1'),
        ),
        migrations.AlterUniqueTogether(
            name='bannerentry',
            unique_together={('banner', 'hero')},
        ),
        migrations.AddConstraint(
            model_name='bannerrewarditem',
            constraint=models.CheckConstraint(condition=models.Q(('min_amount__gt', 0), ('max_amount__gte', models.F('min_amount'))), name='reward_item_min_le_max'),
        ),
    ]
