# Generated by Django 5.1.6 on 2025-09-04 17:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_banner_bannerentry_bannerpulllog_bannerreward_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Raid Room', max_length=100)),
                ('max_players', models.PositiveIntegerField(default=2)),
                ('state', models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('wave_index', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tick_interval_ms', models.PositiveIntegerField(default=1000)),
                ('last_tick_at', models.DateTimeField(blank=True, null=True)),
                ('random_seed', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_raids', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='RaidParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ready', models.BooleanField(default=False)),
                ('is_alive', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playerhero')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raid_participations', to='core.member')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.raidroom')),
            ],
            options={
                'unique_together': {('room', 'member')},
            },
        ),
        migrations.CreateModel(
            name='RaidEnemyInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.PositiveIntegerField(default=0)),
                ('max_hp', models.PositiveIntegerField(default=0)),
                ('speed', models.IntegerField(default=100)),
                ('is_alive', models.BooleanField(default=True)),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enemy')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='core.raidroom')),
            ],
        ),
        migrations.CreateModel(
            name='RaidTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('actor_type', models.CharField(choices=[('hero', 'Hero'), ('enemy', 'Enemy')], max_length=10)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('enemy_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.raidenemyinstance')),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.raidparticipant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.raidroom')),
            ],
            options={
                'ordering': ['room_id', 'index'],
                'unique_together': {('room', 'index')},
            },
        ),
        migrations.CreateModel(
            name='RaidDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(blank=True, default='', max_length=20)),
                ('action_type', models.CharField(max_length=30)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.raidparticipant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_logs', to='core.raidroom')),
                ('turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.raidturn')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
