# Generated by Django 5.1.6 on 2025-09-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_raidroom_raidparticipant_raidenemyinstance_raidturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerhero',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
    ]
