# Generated by Django 5.1.6 on 2025-09-04 18:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_playerhero_current_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidroom',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raidroom',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Equipo', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='TeamSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('player_hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_slots', to='core.playerhero')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='core.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('owner',), name='one_active_team_per_member'),
        ),
        migrations.AddConstraint(
            model_name='teamslot',
            constraint=models.UniqueConstraint(fields=('team', 'player_hero'), name='unique_playerhero_per_team'),
        ),
    ]
