# Generated by Django 5.1.6 on 2025-09-06 07:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_raidroom_closed_raidroom_expires_at_team_teamslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='raids/')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('normal', 'Normal'), ('hard', 'Difícil'), ('nightmare', 'Pesadilla')], default='normal', max_length=20)),
                ('min_players', models.PositiveIntegerField(default=1)),
                ('max_players', models.PositiveIntegerField(default=4)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='raidroom',
            name='max_players',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='raidroom',
            name='raid',
            field=models.ForeignKey(blank=True, help_text='Raid estructurada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.raid'),
        ),
        migrations.CreateModel(
            name='RaidWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wave_number', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waves', to='core.raid')),
            ],
            options={
                'ordering': ['raid', 'wave_number'],
                'unique_together': {('raid', 'wave_number')},
            },
        ),
        migrations.CreateModel(
            name='RaidEnemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('level_modifier', models.FloatField(default=1.0, help_text='Multiplicador de nivel (1.0 = nivel base)')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.enemy')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='core.raidwave')),
            ],
        ),
    ]
