# Generated by Django 5.1.6 on 2025-09-06 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_raid_alter_raidroom_max_players_raidroom_raid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidturn',
            name='hero_instance',
            field=models.ForeignKey(blank=True, help_text='Héroe específico que tiene el turno', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.playerhero'),
        ),
        migrations.AlterField(
            model_name='raidroom',
            name='state',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('in_progress', 'In Progress'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
    ]
