# Generated by Django 5.1.6 on 2025-09-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_raidturn_hero_instance_alter_raidroom_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidparticipant',
            name='player_color',
            field=models.PositiveIntegerField(default=1, help_text='Color del jugador (1-4)'),
        ),
    ]
