# Generated by Django 5.1.6 on 2025-09-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_raidparticipant_player_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Ruta estática relativa, ej: img/campamento_principal.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enemy',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Ruta estática relativa, ej: img/enemy_sheep.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Ruta estática relativa, ej: img/hero_male.png', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Ruta estática relativa, ej: img/oro.png', max_length=200, null=True),
        ),
    ]
