# Generated by Django 5.1.6 on 2025-02-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('password_member', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField(max_length=9)),
            ],
        ),
    ]
