# Generated by Django 5.1.6 on 2025-02-23 10:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ability_attack_booster_card_coin_collection_deck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_set', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='set_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.set'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='set_hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.set'),
        ),
    ]
