# Generated by Django 5.1.6 on 2025-02-23 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_set_alter_card_set_card_alter_hero_set_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='ability_card',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ability'),
        ),
        migrations.AddField(
            model_name='hero',
            name='ability_hero',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.ability'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rarity_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rarity'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='rarity_hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rarity'),
        ),
    ]
