# Generated by Django 5.1.1 on 2025-04-02 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_card_attack_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='set_booster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.set'),
        ),
    ]
