# Generated by Django 5.1.1 on 2025-04-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_collectioncard'),
    ]

    operations = [
        migrations.AddField(
            model_name='booster',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
