# Generated by Django 5.1.1 on 2025-04-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_membercoin_total_amount_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(default='cards/default.jpg', upload_to='cards/'),
        ),
    ]
