# Generated by Django 5.1.1 on 2025-08-18 15:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('damage', 'Damage'), ('heal', 'Heal'), ('buff', 'Buff'), ('debuff', 'Debuff')], max_length=50)),
                ('power', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hq', 'Edificio principal'), ('xp_tower_heroes', 'Edificio de gestión para héroes'), ('xp_farming', 'Edificio almacenador de experiéncia'), ('market', 'Mercado'), ('alliance', 'Centro de la alianza'), ('camp', 'Campamento principal'), ('cf', 'Hoguera'), ('store', 'Alijo principal'), ('wc_portal', 'Baño invocador')], max_length=50, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='buildings/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('password_member', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaidEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('enemy_name', models.CharField(max_length=100)),
                ('enemy_hp', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AllianceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_to_join', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('raid_notifications', models.BooleanField(default=True)),
                ('custom_rules', models.TextField(blank=True)),
                ('alliance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.alliance')),
            ],
        ),
        migrations.CreateModel(
            name='AllianceBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='core.alliance')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='enemies/')),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField(default=1)),
                ('base_hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('abilities', models.ManyToManyField(blank=True, to='core.ability')),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='heroes/')),
                ('description', models.TextField()),
                ('base_hp', models.IntegerField()),
                ('base_attack', models.IntegerField(default=50)),
                ('base_defense', models.IntegerField(default=30)),
                ('base_speed', models.IntegerField(default=30)),
                ('abilities', models.ManyToManyField(related_name='heroes', to='core.ability')),
                ('rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rarity')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('stored_xp', models.FloatField(default=0)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_hp', models.IntegerField()),
                ('exp', models.IntegerField(default=0)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hero')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
            ],
        ),
        migrations.CreateModel(
            name='RaidParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_done', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
                ('raid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.raidevent')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype')),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='core.member')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='core.member')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
        migrations.CreateModel(
            name='AllianceMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('co_leader', 'Co-líder'), ('officer', 'Oficial'), ('member', 'Miembro')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.alliance')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alliances', to='core.member')),
            ],
            options={
                'unique_together': {('alliance', 'member')},
            },
        ),
    ]
