# Generated by Django 5.1.1 on 2025-07-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_enemy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='hp',
            new_name='base_hp',
        ),
        migrations.AddField(
            model_name='enemy',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ability'),
        ),
    ]
