# Generated by Django 5.1.1 on 2025-08-18 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_playerbuilding_stored_xp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rarity',
            name='name',
        ),
        migrations.AddField(
            model_name='rarity',
            name='type',
            field=models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=50),
        ),
        migrations.AlterField(
            model_name='hero',
            name='rarity',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rarity'),
        ),
    ]
