# Generated by Django 5.1.1 on 2025-07-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_hp_enemy_base_hp_enemy_ability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerhero',
            name='level',
        ),
        migrations.AddField(
            model_name='hero',
            name='base_attack',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_defense',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='hero',
            name='base_speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='playerhero',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
