# Generated by Django 5.1.1 on 2025-07-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_playerhero_level_hero_base_attack_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='ability',
        ),
        migrations.AddField(
            model_name='hero',
            name='abilities',
            field=models.ManyToManyField(related_name='heroes', to='core.ability'),
        ),
    ]
