# Generated by Django 5.1.1 on 2025-07-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_hero_ability_hero_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='ability',
        ),
        migrations.AddField(
            model_name='enemy',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='core.ability'),
        ),
    ]
