# Generated by Django 5.1.1 on 2025-07-28 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_enemy_ability_enemy_abilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='enemies/'),
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='heroes/'),
        ),
    ]
