# Generated by Django 5.1.1 on 2025-07-28 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_enemy_image_hero_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('hq', 'Edificio principal'), ('xp_tower_heroes', 'Edificio de gestión para héroes'), ('xp_farming', 'Edificio almacenador de experiéncia'), ('market', 'Mercado')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='playerbuilding',
            name='building',
        ),
        migrations.RemoveField(
            model_name='playerbuilding',
            name='upgraded_at',
        ),
        migrations.AddField(
            model_name='playerbuilding',
            name='stored_xp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerbuilding',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype'),
        ),
    ]
