# Generated by Django 5.1.1 on 2025-07-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_buildingtype_remove_playerbuilding_building_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.AddField(
            model_name='buildingtype',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen PNG con fondo transparente que represente este tipo de edificio', null=True, upload_to='buildings/'),
        ),
        migrations.AlterField(
            model_name='buildingtype',
            name='type',
            field=models.CharField(choices=[('hq', 'Edificio principal'), ('xp_tower_heroes', 'Edificio de gestión para héroes'), ('xp_farming', 'Edificio almacenador de experiéncia'), ('market', 'Mercado'), ('alliance', 'Centro de la alianza')], max_length=50, unique=True),
        ),
    ]
